use base64::{engine::general_purpose::STANDARD, Engine};
use nodeeasy_core::{Node, Protocol};
use serde::Serialize;
use serde_json::{json, Value};
use crate::secrets::SecretMaterial;

#[derive(Serialize)] pub struct ExportNode<'a> { pub id:String, pub name:Option<&'a String>, pub protocol:String, pub host:&'a str, pub port:u16, pub score:f64, pub status:String }
pub fn json(nodes:&[Node])->String{serde_json::to_string_pretty(&nodes.iter().map(|n|ExportNode{id:n.id.to_string(),name:n.name.as_ref(),protocol:format!("{:?}",n.protocol).to_lowercase(),host:&n.endpoint.host,port:n.endpoint.port,score:n.score,status:format!("{:?}",n.status).to_lowercase()}).collect::<Vec<_>>()).unwrap_or_else(|_|"[]".into())}
pub fn share_target(node:&Node)->String{format!("nodeeasy://node/{}",node.id)}
pub fn qr_ascii(node:&Node)->Result<String,Box<dyn std::error::Error+Send+Sync>>{let code=qrcode::QrCode::new(share_target(node).as_bytes())?;Ok(code.render::<qrcode::render::unicode::Dense1x2>().quiet_zone(false).build())}
fn s(v:&Value,k:&str)->Option<String>{v.get(k).and_then(Value::as_str).map(ToOwned::to_owned)}fn required(v:&Value,k:&str)->Result<String,String>{s(v,k).ok_or_else(||format!("missing secret option: {k}"))}
fn mihomo_type(p:Protocol)->&'static str{match p{Protocol::Shadowsocks|Protocol::Shadowsocks2022=>"ss",Protocol::Vmess=>"vmess",Protocol::Vless=>"vless",Protocol::Trojan=>"trojan",Protocol::Hysteria=>"hysteria",Protocol::Hysteria2=>"hysteria2",Protocol::Tuic=>"tuic",Protocol::Wireguard=>"wireguard",Protocol::Socks5=>"socks5",Protocol::Http=>"http",Protocol::AnyTls=>"anytls"}}
pub fn mihomo(node:&Node,secret:Option<&SecretMaterial>)->Result<String,String>{let o=secret.map(|s|&s.options).ok_or("credentials are required for config export")?;let mut m=serde_yaml::Mapping::new();m.insert(serde_yaml::Value::String("name".into()),serde_yaml::Value::String(node.name.clone().unwrap_or_else(||node.id.to_string())));m.insert(serde_yaml::Value::String("type".into()),serde_yaml::Value::String(mihomo_type(node.protocol).into()));m.insert(serde_yaml::Value::String("server".into()),serde_yaml::Value::String(node.endpoint.host.clone()));m.insert(serde_yaml::Value::String("port".into()),serde_yaml::Value::Number(serde_yaml::Number::from(node.endpoint.port as u64)));for(k,v)in o.as_object().ok_or("secret options must be an object")?{m.insert(serde_yaml::Value::String(k.clone()),serde_yaml::to_value(v).map_err(|e|e.to_string())?);}let body=serde_yaml::to_string(&vec![serde_yaml::Value::Mapping(m)]).map_err(|e|e.to_string())?;Ok(format!("proxies:\n{body}"))}
pub fn sing_box(node:&Node,secret:Option<&SecretMaterial>)->Result<String,String>{let o=secret.map(|s|&s.options).ok_or("credentials are required for config export")?;let mut out=json!({"type":mihomo_type(node.protocol),"tag":node.name.clone().unwrap_or_else(||node.id.to_string()),"server":node.endpoint.host,"server_port":node.endpoint.port});if let Some(obj)=o.as_object()&&let Some(map)=out.as_object_mut(){for(k,v)in obj{map.insert(k.clone(),v.clone());}}serde_json::to_string_pretty(&json!({"outbounds":[out]})).map_err(|e|e.to_string())}
pub fn v2ray_uri(node:&Node,secret:Option<&SecretMaterial>)->Result<String,String>{let o=secret.map(|s|&s.options).ok_or("credentials are required for URI export")?;let name=node.name.clone().unwrap_or_else(||node.id.to_string());let enc=urlencoding(&name);let uri=match node.protocol{Protocol::Vless=>{let id=required(o,"uuid")?;format!("vless://{id}@{}:{}?{}#{enc}",node.endpoint.host,node.endpoint.port,query(o))},Protocol::Trojan=>{let password=required(o,"password")?;format!("trojan://{password}@{}:{}?{}#{enc}",node.endpoint.host,node.endpoint.port,query(o))},Protocol::Vmess=>{let id=required(o,"uuid")?;let obj=json!({"v":"2","ps":name,"add":node.endpoint.host,"port":node.endpoint.port.to_string(),"id":id,"aid":s(o,"aid").unwrap_or_else(||"0".into()),"net":s(o,"network").unwrap_or_else(||"tcp".into()),"type":s(o,"type").unwrap_or_else(||"none".into()),"tls":s(o,"tls").unwrap_or_default()});format!("vmess://{}",STANDARD.encode(serde_json::to_vec(&obj).map_err(|e|e.to_string())?))},_=>return Err("V2Ray URI exporter currently supports VMess, VLESS and Trojan".into())};Ok(uri)}
fn query(o:&Value)->String{let Some(m)=o.as_object()else{return String::new()};m.iter().filter_map(|(k,v)|v.as_str().map(|x|format!("{}={}",urlencoding(k),urlencoding(x)))).collect::<Vec<_>>().join("&")}
fn urlencoding(s:&str)->String{s.bytes().map(|b|match b{b'A'..=b'Z'|b'a'..=b'z'|b'0'..=b'9'|b'-'|b'_'|b'.'|b'~'=>char::from(b).to_string(),_=>format!("%{b:02X}")}).collect()}
