use crate::events::{AppEvent, EventBus};
use crate::probe::{self, Observation, ProbeConfig};
use crate::repository;
use chrono::Utc;
use nodeeasy_core::{score, Node, NodeTest, TestType};
use sqlx::SqlitePool;
use std::{collections::HashSet, sync::Arc};
use tokio::sync::Semaphore;
use tokio_util::sync::CancellationToken;
use uuid::Uuid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BatchRequest { pub node_ids: Vec<Uuid>, pub concurrency: Option<usize>, pub probes: Option<Vec<TestType>>, pub config: Option<ProbeConfig> }
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BatchResult { pub job_id: Uuid, pub completed: usize, pub successful: usize, pub cancelled: bool }

pub async fn persist(pool:&SqlitePool,node_id:Uuid,o:&Observation)->Result<NodeTest,sqlx::Error>{let test=NodeTest{id:Uuid::new_v4(),node_id,test_type:o.test_type,latency_ms:o.latency_ms,download_bps:o.download_bps,upload_bps:None,success:o.success,error:o.error.clone(),tested_at:Utc::now(),duration_ms:Some(o.duration_ms)};sqlx::query("INSERT INTO node_tests(id,node_id,test_type,latency_ms,download_bps,upload_bps,success,error,tested_at,duration_ms) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(test.id.to_string()).bind(test.node_id.to_string()).bind(format!("{:?}",test.test_type).to_lowercase()).bind(test.latency_ms).bind(test.download_bps).bind(test.upload_bps).bind(test.success).bind(&test.error).bind(test.tested_at).bind(test.duration_ms.map(|v|v as i64)).execute(pool).await?;Ok(test)}

pub async fn run_batch(pool:SqlitePool,bus:Arc<EventBus>,request:BatchRequest,cancel:CancellationToken)->Result<BatchResult,String>{let job_id=Uuid::new_v4();let concurrency=request.concurrency.unwrap_or(8).clamp(1,32);let sem=Arc::new(Semaphore::new(concurrency));let nodes=repository::list_nodes(&pool,10000).await.map_err(|e|e.to_string())?;let wanted:HashSet<Uuid>=request.node_ids.into_iter().collect();let nodes:Vec<Node>=nodes.into_iter().filter(|n|wanted.contains(&n.id)).collect();let cfg=request.config.unwrap_or_default();let probes=request.probes.unwrap_or_else(||vec![TestType::Tcp,TestType::Tls,TestType::Http,TestType::Latency,TestType::Stability]);bus.publish(AppEvent::JobStarted{job_id:job_id.to_string(),kind:"batch_test".into()});let mut set=tokio::task::JoinSet::new();let total=nodes.len()*probes.len();let mut completed=0usize;let mut successful=0usize;for node in nodes{let node_id=node.id;let host=node.endpoint.host.clone();let port=node.endpoint.port;for kind in probes.iter().copied(){let permit=sem.clone().acquire_owned().await.map_err(|e|e.to_string())?;let pool=pool.clone();let bus=bus.clone();let cancel=cancel.clone();let cfg=cfg.clone();let host=host.clone();set.spawn(async move{let _permit=permit;if cancel.is_cancelled(){return Ok::<bool,String>(false)}let o=match kind{TestType::Tcp=>probe::tcp(&host,port,&cfg,&cancel).await,TestType::Tls=>probe::tls(&host,port,&cfg,&cancel).await,TestType::Http=>probe::http(&host,port,&cfg,&cancel).await,TestType::Latency=>probe::latency(&host,port,&cfg,&cancel).await,TestType::Download=>probe::download(&cfg,&cancel).await,TestType::Stability=>probe::stability(&host,port,&cfg,&cancel).await};let ok=o.success;persist(&pool,node_id,&o).await.map_err(|e|e.to_string())?;bus.publish(AppEvent::NodeTested{node_id:node_id.to_string(),success:ok,latency_ms:o.latency_ms});Ok(ok)});}}while let Some(r)=set.join_next().await{completed+=1;if r.map_err(|e|e.to_string())??{successful+=1}bus.publish(AppEvent::JobProgress{job_id:job_id.to_string(),completed:completed as u64,total:total as u64});if cancel.is_cancelled(){set.abort_all();break}}bus.publish(AppEvent::JobFinished{job_id:job_id.to_string(),success:!cancel.is_cancelled()});Ok(BatchResult{job_id,completed,successful,cancelled:cancel.is_cancelled()})}

pub async fn recompute_score(pool:&SqlitePool,node_id:Uuid)->Result<score::ScoreBreakdown,sqlx::Error>{let tests=sqlx::query_as::<_,(String,Option<f64>,Option<f64>,i64)>("SELECT test_type,latency_ms,download_bps,success FROM node_tests WHERE node_id=? ORDER BY tested_at DESC LIMIT 100").bind(node_id.to_string()).fetch_all(pool).await?;let mut latency:Option<f64>=None;let mut speed:Option<f64>=None;let mut successes=0usize;let mut total=0usize;for(t,l,d,s)in tests{total+=1;if s!=0{successes+=1}if latency.is_none()&&t=="latency"{latency=l}if speed.is_none()&&t=="download"{speed=d}}let stability=if total==0{0.0}else{successes as f64/total as f64};let breakdown=score::calculate_breakdown(score::ScoreInput{availability:if stability>0.0{1.0}else{0.0},latency_ms:latency,download_bps:speed,stability,freshness:1.0});let now=Utc::now();sqlx::query("UPDATE nodes SET score=?,updated_at=? WHERE id=?").bind(breakdown.total).bind(now).bind(node_id.to_string()).execute(pool).await?;sqlx::query("INSERT INTO score_history(id,node_id,total,availability,latency,download,stability,freshness,calculated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(Uuid::new_v4().to_string()).bind(node_id.to_string()).bind(breakdown.total).bind(breakdown.availability).bind(breakdown.latency).bind(breakdown.download).bind(breakdown.stability).bind(breakdown.freshness).bind(now).execute(pool).await?;Ok(breakdown)}
