use async_trait::async_trait;
use nodeeasy_core::{Node, TestType};
use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::{net::IpAddr, time::Duration};
use tokio::net::TcpStream;
use tokio_util::sync::CancellationToken;
use url::Url;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProbeConfig { pub timeout_ms:u64,pub attempts:u32,pub http_path:String,pub download_url:Option<String> }
impl Default for ProbeConfig{fn default()->Self{Self{timeout_ms:5000,attempts:3,http_path:"/".into(),download_url:None}}}
#[derive(Debug,Clone,Serialize,Deserialize)]
pub struct Observation{pub test_type:TestType,pub success:bool,pub latency_ms:Option<f64>,pub download_bps:Option<f64>,pub duration_ms:u64,pub bytes:u64,pub attempts:u32,pub error:Option<String>}
#[async_trait]
pub trait Probe:Send+Sync{fn kind(&self)->TestType;async fn run(&self,node:&Node,config:&ProbeConfig,cancel:&CancellationToken)->Observation;}
pub struct TcpProbe;pub struct TlsProbe;pub struct HttpProbe;pub struct LatencyProbe;pub struct DownloadProbe;pub struct StabilityProbe;
#[async_trait]impl Probe for TcpProbe{fn kind(&self)->TestType{TestType::Tcp}async fn run(&self,n:&Node,c:&ProbeConfig,x:&CancellationToken)->Observation{tcp(&n.endpoint.host,n.endpoint.port,c,x).await}}
#[async_trait]impl Probe for TlsProbe{fn kind(&self)->TestType{TestType::Tls}async fn run(&self,n:&Node,c:&ProbeConfig,x:&CancellationToken)->Observation{tls(&n.endpoint.host,n.endpoint.port,c,x).await}}
#[async_trait]impl Probe for HttpProbe{fn kind(&self)->TestType{TestType::Http}async fn run(&self,n:&Node,c:&ProbeConfig,x:&CancellationToken)->Observation{http(&n.endpoint.host,n.endpoint.port,c,x).await}}
#[async_trait]impl Probe for LatencyProbe{fn kind(&self)->TestType{TestType::Latency}async fn run(&self,n:&Node,c:&ProbeConfig,x:&CancellationToken)->Observation{latency(&n.endpoint.host,n.endpoint.port,c,x).await}}
#[async_trait]impl Probe for StabilityProbe{fn kind(&self)->TestType{TestType::Stability}async fn run(&self,n:&Node,c:&ProbeConfig,x:&CancellationToken)->Observation{stability(&n.endpoint.host,n.endpoint.port,c,x).await}}
#[async_trait]impl Probe for DownloadProbe{fn kind(&self)->TestType{TestType::Download}async fn run(&self,_:&Node,c:&ProbeConfig,x:&CancellationToken)->Observation{download(c,x).await}}
fn attempts(n:u32)->u32{n.clamp(1,20)}fn timeout(c:&ProbeConfig)->Duration{Duration::from_millis(c.timeout_ms.clamp(250,60_000))}
async fn public_host(host:&str,port:u16)->Result<(),String>{if host.eq_ignore_ascii_case("localhost")||host.ends_with(".localhost"){return Err("private target blocked".into())}let ips=tokio::time::timeout(Duration::from_secs(2),tokio::net::lookup_host((host,port))).await.map_err(|_|"DNS lookup timed out".to_string())?.map_err(|e|e.to_string())?;let mut seen=false;for addr in ips{seen=true;if nodeeasy_core::is_private_ip(&addr.ip().to_string()){return Err("private target blocked".into())}}if !seen{Err("target did not resolve".into())}else{Ok(())}}
pub async fn tcp(host:&str,port:u16,c:&ProbeConfig,cancel:&CancellationToken)->Observation{let started=std::time::Instant::now();if let Err(e)=public_host(host,port).await{return failed(TestType::Tcp,e)}let fut=TcpStream::connect((host,port));let result=tokio::select!{_=cancel.cancelled()=>return failed(TestType::Tcp,"cancelled".into()),r=tokio::time::timeout(timeout(c),fut)=>r};let success=matches!(result,Ok(Ok(_)));Observation{test_type:TestType::Tcp,success,latency_ms:success.then(||started.elapsed().as_secs_f64()*1000.0),download_bps:None,duration_ms:started.elapsed().as_millis()as u64,bytes:0,attempts:1,error:(!success).then_some("tcp connect failed or timed out".into())}}
fn endpoint_url(scheme:&str,host:&str,port:u16,path:&str)->Result<Url,String>{let url=Url::parse(&format!("{scheme}://{host}:{port}{path}")).map_err(|e|e.to_string())?;validate_public_target(&url)?;Ok(url)}
pub fn validate_public_target(url:&Url)->Result<(),String>{if !matches!(url.scheme(),"http"|"https"){return Err("only http/https targets are allowed".into())}let host=url.host_str().ok_or("target has no host")?;if host.eq_ignore_ascii_case("localhost")||host.ends_with(".localhost"){return Err("private target blocked".into())}if let Ok(ip)=host.parse::<IpAddr>(){if nodeeasy_core::is_private_ip(&ip.to_string()){return Err("private target blocked".into())}}Ok(())}
pub async fn tls(host:&str,port:u16,c:&ProbeConfig,x:&CancellationToken)->Observation{if let Err(e)=public_host(host,port).await{return failed(TestType::Tls,e)}http_like(TestType::Tls,endpoint_url("https",host,port,"/"),c,x).await}
pub async fn http(host:&str,port:u16,c:&ProbeConfig,x:&CancellationToken)->Observation{if let Err(e)=public_host(host,port).await{return failed(TestType::Http,e)}let path=if c.http_path.starts_with('/'){c.http_path.as_str()}else{"/"};http_like(TestType::Http,endpoint_url("http",host,port,path),c,x).await}
fn failed(kind:TestType,error:String)->Observation{Observation{test_type:kind,success:false,latency_ms:None,download_bps:None,duration_ms:0,bytes:0,attempts:1,error:Some(error)}}
async fn http_like(kind:TestType,target:Result<Url,String>,c:&ProbeConfig,x:&CancellationToken)->Observation{let started=std::time::Instant::now();let target=match target{Ok(v)=>v,Err(e)=>return failed(kind,e)};let client=match Client::builder().timeout(timeout(c)).redirect(reqwest::redirect::Policy::limited(3)).build(){Ok(v)=>v,Err(e)=>return failed(kind,e.to_string())};let result=tokio::select!{_=x.cancelled()=>return failed(kind,"cancelled".into()),r=client.get(target).send()=>r};match result{Ok(resp)=>{let ok=resp.status().is_success();Observation{test_type:kind,success:ok,latency_ms:Some(started.elapsed().as_secs_f64()*1000.0),download_bps:None,duration_ms:started.elapsed().as_millis()as u64,bytes:0,attempts:1,error:(!ok).then(||format!("http status {}",resp.status()))}},Err(e)=>failed(kind,e.to_string())}}
pub async fn latency(host:&str,port:u16,c:&ProbeConfig,x:&CancellationToken)->Observation{let started=std::time::Instant::now();let n=attempts(c.attempts);let mut samples=Vec::new();for _ in 0..n{let o=tcp(host,port,c,x).await;if x.is_cancelled(){return failed(TestType::Latency,"cancelled".into())}if let Some(v)=o.latency_ms{samples.push(v)}}samples.sort_by(|a,b|a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));let median=samples.get(samples.len()/2).copied();Observation{test_type:TestType::Latency,success:median.is_some(),latency_ms:median,download_bps:None,duration_ms:started.elapsed().as_millis()as u64,bytes:0,attempts:n,error:median.is_none().then_some("no successful latency samples".into())}}
pub async fn stability(host:&str,port:u16,c:&ProbeConfig,x:&CancellationToken)->Observation{let started=std::time::Instant::now();let n=attempts(c.attempts.max(5));let mut ok=0;for _ in 0..n{if tcp(host,port,c,x).await.success{ok+=1}tokio::time::sleep(Duration::from_millis(100)).await}let ratio=ok as f64/n as f64;Observation{test_type:TestType::Stability,success:ratio>=0.8,latency_ms:None,download_bps:Some(ratio),duration_ms:started.elapsed().as_millis()as u64,bytes:0,attempts:n,error:(ratio<0.8).then(||format!("stability {:.0}%",ratio*100.0))}}
pub async fn download(c:&ProbeConfig,x:&CancellationToken)->Observation{let started=std::time::Instant::now();let Some(raw)=&c.download_url else{return failed(TestType::Download,"download_url is required".into())};let Ok(url)=Url::parse(raw)else{return failed(TestType::Download,"invalid download URL".into())};if let Err(e)=validate_public_target(&url){return failed(TestType::Download,e)}let client=match Client::builder().timeout(timeout(c)).build(){Ok(v)=>v,Err(e)=>return failed(TestType::Download,e.to_string())};let response=tokio::select!{_=x.cancelled()=>return failed(TestType::Download,"cancelled".into()),r=client.get(url).send()=>r};match response{Ok(mut r)=>{if !r.status().is_success(){return failed(TestType::Download,format!("http status {}",r.status()))}let mut total=0u64;loop{let chunk=tokio::select!{_=x.cancelled()=>return failed(TestType::Download,"cancelled".into()),v=r.chunk()=>v};match chunk{Ok(Some(b))=>{total+=b.len()as u64;if total>=100*1024*1024{break}},Ok(None)=>break,Err(e)=>return failed(TestType::Download,e.to_string())}}let secs=started.elapsed().as_secs_f64().max(0.001);Observation{test_type:TestType::Download,success:total>0,latency_ms:None,download_bps:Some(total as f64*8.0/secs),duration_ms:started.elapsed().as_millis()as u64,bytes:total,attempts:1,error:None}},Err(e)=>failed(TestType::Download,e.to_string())}}
