<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
type Node={id:string;name?:string;protocol:string;endpoint:{host:string;port:number};status:string;score:number}
type Score={total:number;availability:number;latency:number;download:number;stability:number;freshness:number}
type Test={id:string;test_type:string;success:boolean;error?:string}
type Source={id:string;name:string;kind:string;url:string;last_error?:string|null}
const nodes=ref<Node[]>([]),sources=ref<Source[]>([]),loading=ref(true),online=ref(false),selected=ref<Node|null>(null),score=ref<Score|null>(null),history=ref<Test[]>([]),busy=ref(false),sourceKind=ref('github_raw'),sourceName=ref('GitHub public source'),sourceUrl=ref(''),importBody=ref(''),importName=ref('manual'),engine=ref('mihomo'),engineConfig=ref(''),notice=ref('')
const healthy=computed(()=>nodes.value.filter(n=>n.status==='healthy').length),average=computed(()=>nodes.value.length?nodes.value.reduce((a,n)=>a+n.score,0)/nodes.value.length:0)
async function load(){loading.value=true;try{const [n,s]=await Promise.all([fetch('/api/v1/nodes'),fetch('/api/v1/sources')]);nodes.value=(await n.json()).items;sources.value=(await s.json()).items}finally{loading.value=false}}
async function inspect(n:Node){selected.value=n;score.value=null;history.value=[];const [s,h]=await Promise.all([fetch(`/api/v1/nodes/${n.id}/score`,{method:'POST'}),fetch(`/api/v1/nodes/${n.id}/history`)]);if(s.ok)score.value=await s.json();if(h.ok)history.value=(await h.json()).items}
async function test(n:Node){busy.value=true;try{await fetch(`/api/v1/nodes/${n.id}/test`,{method:'POST'});await load();const fresh=nodes.value.find(x=>x.id===n.id);if(fresh)await inspect(fresh)}finally{busy.value=false}}
async function addSource(){notice.value='';const r=await fetch('/api/v1/sources',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:sourceName.value,kind:sourceKind.value,url:sourceUrl.value})});notice.value=r.ok?'Source added':'Source failed';if(r.ok)await load()}
async function syncSource(s:Source){notice.value='';const r=await fetch(`/api/v1/sources/${s.id}/sync`,{method:'POST'});notice.value=r.ok?'Source synced':'Source sync failed';await load()}
async function manualImport(){const r=await fetch('/api/v1/sources/import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:importName.value,body:importBody.value,kind:'manual'})});notice.value=r.ok?'Imported':'Import failed';if(r.ok){importBody.value='';await load()}}
async function buildEngine(){if(!selected.value)return;const r=await fetch('/api/v1/engines/config',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({engine:engine.value,node_id:selected.value.id})});if(r.ok){const data=await r.json();engineConfig.value=typeof data.config==='string'?data.config:JSON.stringify(data.config??data,null,2)}else{engineConfig.value='engine config unavailable'}}
onMounted(async()=>{await load();try{const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/v1/ws`);ws.onopen=()=>online.value=true;ws.onclose=()=>online.value=false;ws.onmessage=()=>load()}catch{}})
</script>
<template>
<main class="min-h-screen bg-slate-950 text-slate-100 p-6 md:p-10"><header class="flex flex-wrap items-center justify-between gap-4 mb-8"><div><p class="text-cyan-400 text-sm font-semibold tracking-widest">NODEEASY V3.2</p><h1 class="text-3xl font-bold">节点数据中心</h1><p class="text-slate-400 mt-1">采集 · 解析 · 测量 · 评分 · 引擎适配 · 导出</p></div><div class="rounded-full border border-slate-700 px-4 py-2 text-sm"><span :class="online?'text-emerald-400':'text-slate-500'">●</span> API {{online?'connected':'offline'}}</div></header>
<section class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8"><article class="rounded-2xl bg-slate-900 border border-slate-800 p-5"><p class="text-slate-400">节点总数</p><strong class="text-4xl">{{nodes.length}}</strong></article><article class="rounded-2xl bg-slate-900 border border-slate-800 p-5"><p class="text-slate-400">健康节点</p><strong class="text-4xl text-emerald-400">{{healthy}}</strong></article><article class="rounded-2xl bg-slate-900 border border-slate-800 p-5"><p class="text-slate-400">平均评分</p><strong class="text-4xl">{{average.toFixed(1)}}</strong></article></section>
<section class="grid xl:grid-cols-[1fr_420px] gap-6"><div class="space-y-6"><div class="rounded-2xl bg-slate-900 border border-slate-800 p-5"><div class="flex flex-wrap gap-2 mb-3"><select v-model="sourceKind" class="bg-slate-800 rounded px-3 py-2"><option value="github_raw">GitHub raw</option><option value="http_subscription">HTTP subscription</option><option value="local_file">Local file</option></select><input v-model="sourceName" placeholder="Source name" class="bg-slate-800 rounded px-3 py-2 flex-1 min-w-40"><input v-model="sourceUrl" placeholder="URL or local path" class="bg-slate-800 rounded px-3 py-2 flex-[2] min-w-60"><button class="bg-cyan-500 text-slate-950 font-semibold rounded px-4" @click="addSource">添加源</button></div><div class="flex flex-wrap gap-2"><input v-model="importName" placeholder="Manual name" class="bg-slate-800 rounded px-3 py-2"><textarea v-model="importBody" placeholder="粘贴 URI / Base64 / Clash YAML / JSON" class="bg-slate-800 rounded px-3 py-2 flex-1 min-h-20"></textarea><button class="bg-slate-700 rounded px-4" @click="manualImport">手动导入</button></div><p v-if="notice" class="text-xs text-cyan-400 mt-2">{{notice}}</p><div class="mt-4 space-y-2"><div v-for="s in sources" :key="s.id" class="flex items-center gap-3 text-sm border-t border-slate-800 pt-2"><span class="text-slate-400">{{s.kind}}</span><span class="flex-1 truncate">{{s.name}}</span><button class="text-cyan-400" @click="syncSource(s)">同步</button></div></div></div>
<div class="rounded-2xl bg-slate-900 border border-slate-800 overflow-hidden"><div class="px-5 py-4 border-b border-slate-800 flex justify-between"><h2 class="font-semibold">节点列表</h2><button class="text-cyan-400" @click="load">刷新</button></div><div v-if="loading" class="p-8 text-slate-400">Loading...</div><table v-else class="w-full text-sm"><thead class="text-slate-500"><tr><th class="text-left p-4">名称</th><th class="text-left p-4">协议</th><th class="text-left p-4">Endpoint</th><th class="text-left p-4">状态</th><th class="text-right p-4">评分</th></tr></thead><tbody><tr v-for="n in nodes" :key="n.id" @click="inspect(n)" class="border-t border-slate-800 hover:bg-slate-800/60 cursor-pointer"><td class="p-4">{{n.name||'Unnamed'}}</td><td class="p-4 uppercase">{{n.protocol}}</td><td class="p-4 font-mono">{{n.endpoint.host}}:{{n.endpoint.port}}</td><td class="p-4">{{n.status}}</td><td class="p-4 text-right font-semibold">{{n.score.toFixed(1)}}</td></tr></tbody></table></div></div>
<aside class="rounded-2xl bg-slate-900 border border-slate-800 p-5 h-fit"><div v-if="!selected" class="text-slate-500">选择一个节点查看 Score 2.0、测试历史和引擎配置。</div><template v-else><div class="flex justify-between items-start"><div><h2 class="font-semibold">{{selected.name||'Unnamed'}}</h2><p class="text-xs text-slate-500 font-mono mt-1">{{selected.endpoint.host}}:{{selected.endpoint.port}}</p></div><button class="text-xs text-cyan-400" :disabled="busy" @click="test(selected)">{{busy?'测试中…':'重新测试'}}</button></div><div class="mt-5 text-center"><div class="text-5xl font-bold">{{(score?.total??selected.score).toFixed(1)}}</div><div class="text-xs text-slate-500">Score 2.0 / 100</div></div><div v-if="score" class="space-y-3 mt-6"><div v-for="item in [{k:'availability',v:score.availability},{k:'latency',v:score.latency},{k:'download',v:score.download},{k:'stability',v:score.stability},{k:'freshness',v:score.freshness}]" :key="item.k"><div class="flex justify-between text-xs mb-1"><span class="text-slate-400 capitalize">{{item.k}}</span><span>{{item.v.toFixed(1)}}</span></div><div class="h-1.5 bg-slate-800 rounded-full overflow-hidden"><div class="h-full bg-cyan-400" :style="{width:`${Math.min(100,item.v/Math.max(1,item.k==='availability'?30:item.k==='latency'?20:item.k==='download'?25:item.k==='stability'?20:5)*100)}%`}"></div></div></div></div><div class="mt-6"><h3 class="text-sm font-semibold mb-3">Engine adapter</h3><div class="flex gap-2"><select v-model="engine" class="bg-slate-800 rounded px-3 py-2"><option value="mihomo">Mihomo</option><option value="sing-box">sing-box</option><option value="xray">Xray</option></select><button class="bg-slate-700 rounded px-3" @click="buildEngine">生成配置</button></div><pre v-if="engineConfig" class="mt-3 max-h-56 overflow-auto text-xs bg-slate-950 rounded p-3">{{engineConfig}}</pre></div><div class="mt-6"><h3 class="text-sm font-semibold mb-3">最近测试</h3><div v-if="!history.length" class="text-xs text-slate-500">暂无测试记录</div><div v-for="h in history.slice(0,8)" :key="h.id" class="flex justify-between text-xs py-2 border-b border-slate-800"><span>{{h.test_type}}</span><span :class="h.success?'text-emerald-400':'text-rose-400'">{{h.success?'OK':(h.error||'failed')}}</span></div></div></template></aside></section></main>
</template>
