<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'

type Node = { id:string; name?:string; protocol:string; endpoint:{host:string;port:number}; status:string; score:number; last_tested_at?:string }
type Score = { total:number; availability:number; latency:number; download:number; stability:number; freshness:number }
type Test = { id:string; test_type:string; latency_ms?:number; download_bps?:number; success:boolean; error?:string; duration_ms?:number }
const nodes=ref<Node[]>([]),loading=ref(true),online=ref(false),selected=ref<Node|null>(null),score=ref<Score|null>(null),history=ref<Test[]>([]),busy=ref(false)
const healthy=computed(()=>nodes.value.filter(n=>n.status==='healthy').length)
const average=computed(()=>nodes.value.length?nodes.value.reduce((a,n)=>a+n.score,0)/nodes.value.length:0)
async function load(){loading.value=true;try{const r=await fetch('/api/v1/nodes');if(!r.ok)throw Error();nodes.value=(await r.json()).items}finally{loading.value=false}}
async function inspect(n:Node){selected.value=n;score.value=null;history.value=[];const [s,h]=await Promise.all([fetch(`/api/v1/nodes/${n.id}/score` ,{method:'POST'}),fetch(`/api/v1/nodes/${n.id}/history`)]);if(s.ok)score.value=await s.json();if(h.ok)history.value=(await h.json()).items}
async function test(n:Node){busy.value=true;try{await fetch(`/api/v1/nodes/${n.id}/test`,{method:'POST'});await load();const fresh=nodes.value.find(x=>x.id===n.id);if(fresh)await inspect(fresh)}finally{busy.value=false}}
onMounted(async()=>{await load();try{const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/v1/ws`);ws.onopen=()=>online.value=true;ws.onclose=()=>online.value=false;ws.onmessage=()=>load()}catch{}})
</script>
<template>
<main class="min-h-screen bg-slate-950 text-slate-100 p-6 md:p-10"><header class="flex flex-wrap items-center justify-between gap-4 mb-8"><div><p class="text-cyan-400 text-sm font-semibold tracking-widest">NODEEASY V3.1</p><h1 class="text-3xl font-bold">节点数据中心</h1><p class="text-slate-400 mt-1">采集 · 测量 · 评分 · 安全导出</p></div><div class="rounded-full border border-slate-700 px-4 py-2 text-sm"><span :class="online?'text-emerald-400':'text-slate-500'">●</span> API {{online?'connected':'offline'}}</div></header>
<section class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8"><article class="rounded-2xl bg-slate-900 border border-slate-800 p-5"><p class="text-slate-400">节点总数</p><strong class="text-4xl">{{nodes.length}}</strong></article><article class="rounded-2xl bg-slate-900 border border-slate-800 p-5"><p class="text-slate-400">健康节点</p><strong class="text-4xl text-emerald-400">{{healthy}}</strong></article><article class="rounded-2xl bg-slate-900 border border-slate-800 p-5"><p class="text-slate-400">平均评分</p><strong class="text-4xl">{{average.toFixed(1)}}</strong></article></section>
<section class="grid xl:grid-cols-[1fr_380px] gap-6"><div class="rounded-2xl bg-slate-900 border border-slate-800 overflow-hidden"><div class="px-5 py-4 border-b border-slate-800 flex justify-between"><h2 class="font-semibold">节点列表</h2><button class="text-cyan-400" @click="load">刷新</button></div><div v-if="loading" class="p-8 text-slate-400">Loading...</div><table v-else class="w-full text-sm"><thead class="text-slate-500"><tr><th class="text-left p-4">名称</th><th class="text-left p-4">协议</th><th class="text-left p-4">Endpoint</th><th class="text-left p-4">状态</th><th class="text-right p-4">评分</th></tr></thead><tbody><tr v-for="n in nodes" :key="n.id" @click="inspect(n)" class="border-t border-slate-800 hover:bg-slate-800/60 cursor-pointer"><td class="p-4">{{n.name||'Unnamed'}}</td><td class="p-4 uppercase">{{n.protocol}}</td><td class="p-4 font-mono">{{n.endpoint.host}}:{{n.endpoint.port}}</td><td class="p-4">{{n.status}}</td><td class="p-4 text-right font-semibold">{{n.score.toFixed(1)}}</td></tr></tbody></table></div>
<aside class="rounded-2xl bg-slate-900 border border-slate-800 p-5 h-fit"><div v-if="!selected" class="text-slate-500">选择一个节点查看 Score 2.0 和测试历史。</div><template v-else><div class="flex justify-between items-start"><div><h2 class="font-semibold">{{selected.name||'Unnamed'}}</h2><p class="text-xs text-slate-500 font-mono mt-1">{{selected.endpoint.host}}:{{selected.endpoint.port}}</p></div><button class="text-xs text-cyan-400" :disabled="busy" @click="test(selected)">{{busy?'测试中…':'重新测试'}}</button></div><div class="mt-5 text-center"><div class="text-5xl font-bold">{{(score?.total??selected.score).toFixed(1)}}</div><div class="text-xs text-slate-500">Score 2.0 / 100</div></div><div v-if="score" class="space-y-3 mt-6"><div v-for="item in [{k:'availability',v:score.availability},{k:'latency',v:score.latency},{k:'download',v:score.download},{k:'stability',v:score.stability},{k:'freshness',v:score.freshness}]" :key="item.k"><div class="flex justify-between text-xs mb-1"><span class="text-slate-400 capitalize">{{item.k}}</span><span>{{item.v.toFixed(1)}}</span></div><div class="h-1.5 bg-slate-800 rounded-full overflow-hidden"><div class="h-full bg-cyan-400" :style="{width:`${Math.min(100,item.v/Math.max(1,item.k==='availability'?30:item.k==='latency'?20:item.k==='download'?25:item.k==='stability'?20:5)*100)}%`}"></div></div></div></div><div class="mt-6"><h3 class="text-sm font-semibold mb-3">最近测试</h3><div v-if="!history.length" class="text-xs text-slate-500">暂无测试记录</div><div v-for="h in history.slice(0,8)" :key="h.id" class="flex justify-between text-xs py-2 border-b border-slate-800"><span>{{h.test_type}}</span><span :class="h.success?'text-emerald-400':'text-rose-400'">{{h.success?'OK':(h.error||'failed')}}</span></div></div></template></aside></section></main>
</template>
